from setuptools import setup, find_packages

setup(
    name="solar-efficiency-ml",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "xgboost>=1.7.0",
        "lightgbm>=4.0.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.15.0",
        "shap>=0.42.0",
        "optuna>=3.3.0",
        "pyyaml>=6.0",
        "loguru>=0.7.0",
        "pytest>=7.4.0",
        "scipy>=1.11.0",
        "streamlit>=1.28.0",
        "joblib>=1.3.0",
    ],
    author="Ali Khan",
    author_email="akhanfly@gmail.com",  
    description="Physics-informed machine learning pipeline for predicting solar panel efficiency under real-world conditions",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/akhanfly/solar-panel-efficiency-ml",  
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    keywords="solar-energy machine-learning renewable-energy physics-informed-ml photovoltaics",
)
